source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'
# gem 'rails', '4.1.9'
# gem 'grape'
gem 'doorkeeper'
gem 'rails-api'

gem 'sidekiq'
gem 'sidekiq-middleware'

# Use sqlite3 as the database for Active Record
#gem 'sqlite3'
# gem 'mysql2'
gem 'pg'
gem 'pg_search'
# Use SCSS for stylesheets
group :assets do
  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  #gem "fog", require: "fog/aws/storage"
  #gem "asset_sync"
end

# source 'https://rails-assets.org' do
#   gem 'rails-assets-react-router'
#   gem 'rails-assets-react-bootstrap'
#   gem 'rails-assets-react-router-bootstrap'
# end



gem 'bootstrap-sass', '~> 3.3.4'
gem 'autoprefixer-rails'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'






# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'devise', '~> 3.4.1'
gem 'omniauth'
gem "omniauth-google-oauth2"
gem 'omniauth-kakao'

gem 'cancancan', '~> 1.10'
#gem 'simple_form', '3.0.2'
gem 'simple_form', '~> 3.1.0'

gem 'friendly_id', '~> 5.1.0'

gem 'fog', '~> 1.29.0'    #, require: "fog/aws/storage"
gem 'carrierwave', require: true
gem 'carrierwave-ftp', :require => 'carrierwave/storage/sftp' # SFTP only
gem 'mini_magick'
gem 'acts-as-taggable-on', '~> 3.4'

gem 'activerecord-postgis-adapter'
gem "geocoder"
gem 'gmaps4rails'
gem 'redcarpet'
gem 'ckeditor'
# gem 'font-awesome-sass', '~> 4.2.0'
gem "font-awesome-rails"

# gem 'acts_as_votable', '~> 0.10.0'
gem 'rest-client'
gem 'remotipart', '~> 1.2'
gem 'jquery-fileupload-rails', github: 'Springest/jquery-fileupload-rails'


#gem 'owlcarousel-rails'
#gem 'underscore-rails'
# gem 'will_paginate', '~> 3.0.5' #activeadmin conflict!
gem 'kaminari'
gem 'haml-rails'
gem 'react-rails', '~> 1.0'
# gem 'active_model_serializers'
gem 'active_model_serializers', '~> 0.10.0.rc1'
gem "paranoia", "~> 2.0"
gem 'closure_tree'
gem "socialization"
gem "faker"



# group :production do
  # gem 'rack-cache', :require => 'rack/cache'
  # gem 'dalli'
  # gem 'kgio'
  gem 'redis-rails' #Cache, Session, HTTP Cache to Redis
  gem 'redis-rack-cache'
# end

gem 'dotenv-rails'
gem 'lograge'
gem 'remote_syslog_logger'

#push notificatoin
gem 'gcm'
gem 'rpush'
gem 'rpush-redis'

group :development do
	gem "better_errors"
	gem "binding_of_caller"
  gem 'meta_request'
  gem 'letter_opener' # 개발 모드에서 이메일을 보내않고 브라우저에서 미리보기한는 젬
  gem 'quiet_assets'
  # gem "bower-rails", "~> 0.9.2"
end

group :development, :test do
  # gem 'sqlite3'
  gem 'spring'
  gem 'spring-commands-rspec'
  #gem 'rspec-rails', '~> 3.0'
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'celluloid-io'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'cucumber-rails', :require => false
  gem 'database_cleaner'

  #gem 'byebug'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'pry-doc'
  gem 'web-console', '~> 2.0'
  gem 'annotate', '~> 2.6.6'

  # gem 'selenium-webdriver'
  # gem 'headless'
end

gem 'whenever', :require => false
gem "dynamic_sitemaps"

gem 'ransack'
gem 'rails_admin'
gem "responders"
gem 'public_activity'
gem 'activerecord-reputation-system'
gem 'merit'
gem 'recommendable'
gem 'hooks'
gem 'pluck_to_hash'

gem 'newrelic_rpm'

gem 'faraday_middleware'

#gem 'inherited_resources' # replace this to gem "responders" later

# gem 'activeadmin', github: 'activeadmin'
# gem 'active_admin_importable'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'
# gem 'puma', group: [:development, :test]

# group :development do
#     gem 'capistrano',         require: false
#     gem 'capistrano-rvm',     require: false
#     gem 'capistrano-rails',   require: false
#     gem 'capistrano-bundler', require: false
#     gem 'capistrano3-puma',   require: false
#     gem 'capistrano-faster-assets', '~> 1.0'
# end

# Use debugger

group :profile do
  gem 'ruby-prof'
end

# gem 'elasticsearch-model'
# gem 'elasticsearch-rails'

gem 'searchkick'
gem 'twitter-text'

gem 'redis-objects'
gem 'foreman'

gem 'postgres_ext'
gem 'acts-as-taggable-array-on'
gem 'rack-contrib'
gem 'soulmate', :require => 'soulmate/server'
#gem 'soulmate_rails'
gem 'sinatra', :require => nil
gem 'google_places'




###### Job gems ######
# gem 'delayed_job_active_record'
# gem "resque", :require => "resque/server"  
# # gem 'resque-web', require: 'resque_web'# gem "resque", "~> 2.0.0.pre.1", github: "resque/resque"
# gem 'resque-scheduler'
# gem 'resque-loner'













