source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.1'

gem 'aws-sdk-core', '~> 2.0'  
gem 'bcrypt'  
gem 'pg'  

gem 'grape'
# gem 'grape-doorkeeper'
gem 'doorkeeper'
# gem 'rails-api'

gem 'sidekiq'
gem 'sidekiq-middleware'


# Use sqlite3 as the database for Active Record
gem 'sqlite3', group: [:test]

gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

gem "font-awesome-rails"

# group :assets do
#   # Use SCSS for stylesheets
#   gem 'sass-rails', '~> 4.0.3'
#   # Use Uglifier as compressor for JavaScript assets
#   gem 'uglifier', '>= 1.3.0'
#   # Use CoffeeScript for .js.coffee assets and views
#   gem 'coffee-rails', '~> 4.0.0'
#   # See https://github.com/sstephenson/execjs#readme for more supported runtimes

# end

gem "resque", :require => "resque/server"
gem 'resque_mailer'
#gem 'asset_sync', '1.1'

gem 'therubyracer',  platforms: :ruby


# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# gem 'mysql2'
# twitter bootstrap css & javascript toolkit
gem 'twitter-bootswatch-rails', '~> 3.3.2'
gem 'twitter-bootswatch-rails-helpers'
# gem 'will_paginate', '~> 3.0.5'
gem 'haml-rails'

gem 'rest_client'
gem 'meta-tags'
gem 'friendly_id', '~> 5.1.0'

gem 'acts_as_votable', '~> 0.10.0'
gem 'acts_as_commentable_with_threading'
# gem 'simple-rss'

gem 'active_model_serializers', '~> 0.10.0.rc1'
gem "paranoia", "~> 2.0"
gem 'closure_tree'
gem "socialization"
gem "faker"

gem 'devise'
gem 'omniauth'
gem "omniauth-google-oauth2"
gem 'omniauth-kakao'

gem 'cancancan', '~> 1.10'
gem 'simple_form', '3.1'
gem 'social-share-button'

gem 'ckeditor'
gem 'paperclip'

gem 'fog', '~> 1.29.0'    #, require: "fog/aws/storage"
gem 'carrierwave', require: true
gem 'mini_magick'
gem 'acts-as-taggable-on', '~> 3.4'

#env, log gems
gem 'dotenv-rails'
gem 'lograge'
# gem 'remote_syslog_logger'
gem 'rails_12factor', group: :production


# group :production do
  gem 'rack-cache', :require => 'rack/cache'
  gem 'dalli'
  gem 'kgio'
# end

group :development do
	gem "better_errors"
	gem "binding_of_caller"
  gem 'meta_request'
  gem 'letter_opener'
  gem 'quiet_assets'
  gem 'annotate', '~> 2.6.6'
  # gem "bower-rails", "~> 0.9.2"
end

group :development, :test do
  # gem 'sqlite3'
  # gem 'spring'
  # gem 'spring-commands-rspec'
  #gem 'rspec-rails', '~> 3.0'
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'celluloid-io'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'cucumber-rails', :require => false
  gem 'database_cleaner'

  #gem 'byebug'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'pry-doc'
  gem 'web-console', '~> 2.0'

  # gem 'selenium-webdriver'
  # gem 'headless'
end

gem 'whenever', :require => false
gem "dynamic_sitemaps"

gem 'activeadmin', github: 'activeadmin'
gem 'active_admin_importable'
# gem 'ratyrate'
gem 'newrelic_rpm'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'
gem 'puma'

# Use Capistrano for deployment
# group :development do
#     gem 'capistrano',         require: false
#     gem 'capistrano-rvm',     require: false
#     gem 'capistrano-rails',   require: false
#     gem 'capistrano-bundler', require: false
#     # gem "capistrano-resque", "~> 0.2.1", require: false
#     gem 'capistrano-faster-assets', '~> 1.0'
#     # gem 'capistrano3-puma',   require: false
# end

# Use debugger
# gem 'debugger', group: [:development, :test]
# group :development, :test do
#   gem 'byebug'
#   gem 'web-console', '~>2.0'
#   gem 'spring', '~> 1.3.6'
# end
# gem 'elasticsearch-model'
# gem 'elasticsearch-rails'

gem 'searchkick'
gem 'twitter-text'

gem 'redis-objects'
gem 'foreman'

gem 'postgres_ext'
gem 'acts-as-taggable-array-on'
gem 'rack-contrib'
gem 'soulmate', :require => 'soulmate/server'

gem 'merit'


